# Form implementation generated from reading ui file '.\untitled.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def __init__(self):
        self.statusText = None
        self.centralwidget = None
        self.btnAdd = None
        self.inputUrl = None
        self.label = None
        self.inputIp = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 100)
        MainWindow.setMinimumSize(QtCore.QSize(400, 100))
        MainWindow.setMaximumSize(QtCore.QSize(400, 100))
        MainWindow.setBaseSize(QtCore.QSize(400, 100))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnAdd = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnAdd.setGeometry(QtCore.QRect(10, 60, 150, 31))
        self.btnAdd.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btnAdd.setBaseSize(QtCore.QSize(150, 0))
        self.btnAdd.setAutoDefault(False)
        self.btnAdd.setDefault(False)
        self.btnAdd.setFlat(False)
        self.btnAdd.setObjectName("btnAdd")
        self.inputUrl = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.inputUrl.setGeometry(QtCore.QRect(190, 30, 201, 21))
        self.inputUrl.setFrame(False)
        self.inputUrl.setObjectName("inputUrl")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(9, 9, 247, 16))
        self.label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.statusText = QtWidgets.QLabel(parent=self.centralwidget)
        self.statusText.setGeometry(QtCore.QRect(190, 60, 281, 31))
        self.statusText.setMinimumSize(QtCore.QSize(100, 0))
        self.statusText.setBaseSize(QtCore.QSize(100, 0))
        self.statusText.setAutoFillBackground(False)
        self.statusText.setScaledContents(False)
        self.statusText.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.statusText.setWordWrap(True)
        self.statusText.setObjectName("statusText")
        self.inputIp = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.inputIp.setGeometry(QtCore.QRect(10, 30, 171, 21))
        self.inputIp.setFrame(False)
        self.inputIp.setClearButtonEnabled(False)
        self.inputIp.setObjectName("inputIp")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Add hosts rule"))
        self.btnAdd.setText(_translate("MainWindow", "ADD"))
        self.inputUrl.setPlaceholderText(_translate("MainWindow", "URL"))
        self.label.setText(_translate("MainWindow", "Add rule to hosts file"))
        self.statusText.setText(_translate("MainWindow", "Status: On hold, wait for user\'s action"))
        self.inputIp.setPlaceholderText(_translate("MainWindow", "IP address 127.0.0.1 by default"))
