# Form implementation generated from reading ui file '.\untitled.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddRuleWindow(object):
    def setupUi(self, AddRuleWindow):
        AddRuleWindow.setObjectName("AddRuleWindow")
        AddRuleWindow.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        AddRuleWindow.resize(400, 100)
        AddRuleWindow.setMinimumSize(QtCore.QSize(400, 100))
        AddRuleWindow.setMaximumSize(QtCore.QSize(400, 100))
        AddRuleWindow.setBaseSize(QtCore.QSize(400, 100))
        self.centralwidget = QtWidgets.QWidget(parent=AddRuleWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnAdd = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnAdd.setGeometry(QtCore.QRect(10, 60, 381, 31))
        self.btnAdd.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnAdd.setBaseSize(QtCore.QSize(150, 0))
        self.btnAdd.setAutoDefault(False)
        self.btnAdd.setDefault(False)
        self.btnAdd.setFlat(False)
        self.btnAdd.setObjectName("btnAdd")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(9, 9, 247, 16))
        self.label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.inputIp = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.inputIp.setGeometry(QtCore.QRect(10, 30, 381, 21))
        self.inputIp.setFrame(False)
        self.inputIp.setClearButtonEnabled(False)
        self.inputIp.setObjectName("inputIp")
        AddRuleWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AddRuleWindow)
        QtCore.QMetaObject.connectSlotsByName(AddRuleWindow)

    def retranslateUi(self, AddRuleWindow):
        _translate = QtCore.QCoreApplication.translate
        AddRuleWindow.setWindowTitle(_translate("AddRuleWindow", "Add hosts rule"))
        self.btnAdd.setText(_translate("AddRuleWindow", "Add"))
        self.label.setText(_translate("AddRuleWindow", "Enter new line"))
        self.inputIp.setPlaceholderText(_translate("AddRuleWindow", "Enter rule or comment"))
