# Form implementation generated from reading ui file '.\all.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_HostsEditor(object):
    def setupUi(self, HostsEditor):
        HostsEditor.setObjectName("HostsEditor")
        HostsEditor.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(HostsEditor.sizePolicy().hasHeightForWidth())
        HostsEditor.setSizePolicy(sizePolicy)
        HostsEditor.setMinimumSize(QtCore.QSize(800, 600))
        HostsEditor.setMaximumSize(QtCore.QSize(800, 600))
        HostsEditor.setBaseSize(QtCore.QSize(800, 600))
        HostsEditor.setAutoFillBackground(False)
        HostsEditor.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        HostsEditor.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(parent=HostsEditor)
        self.centralwidget.setObjectName("centralwidget")
        self.hostsList = QtWidgets.QListWidget(parent=self.centralwidget)
        self.hostsList.setGeometry(QtCore.QRect(140, 20, 681, 581))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hostsList.sizePolicy().hasHeightForWidth())
        self.hostsList.setSizePolicy(sizePolicy)
        self.hostsList.setMaximumSize(QtCore.QSize(1000, 800))
        self.hostsList.setBaseSize(QtCore.QSize(1000, 800))
        self.hostsList.setObjectName("hostsList")
        self.addBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.addBtn.setGeometry(QtCore.QRect(10, 20, 121, 31))
        self.addBtn.setObjectName("addBtn")
        self.editBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.editBtn.setGeometry(QtCore.QRect(10, 60, 121, 31))
        self.editBtn.setObjectName("editBtn")
        self.deleteBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.deleteBtn.setGeometry(QtCore.QRect(10, 100, 121, 31))
        self.deleteBtn.setObjectName("deleteBtn")
        self.scheduleBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.scheduleBtn.setGeometry(QtCore.QRect(10, 220, 121, 31))
        self.scheduleBtn.setObjectName("scheduleBtn")
        self.ieBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ieBtn.setGeometry(QtCore.QRect(10, 260, 121, 31))
        self.ieBtn.setObjectName("ieBtn")
        self.settingsBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.settingsBtn.setGeometry(QtCore.QRect(10, 300, 121, 31))
        self.settingsBtn.setObjectName("settingsBtn")
        self.exitBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exitBtn.setGeometry(QtCore.QRect(10, 562, 121, 31))
        self.exitBtn.setObjectName("exitBtn")
        self.infoBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.infoBtn.setGeometry(QtCore.QRect(10, 520, 121, 31))
        self.infoBtn.setObjectName("infoBtn")
        self.resetBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.resetBtn.setGeometry(QtCore.QRect(10, 180, 121, 31))
        self.resetBtn.setObjectName("resetBtn")
        self.saveBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.saveBtn.setGeometry(QtCore.QRect(10, 140, 121, 31))
        self.saveBtn.setObjectName("saveBtn")
        HostsEditor.setCentralWidget(self.centralwidget)

        self.retranslateUi(HostsEditor)
        QtCore.QMetaObject.connectSlotsByName(HostsEditor)

    def retranslateUi(self, HostsEditor):
        _translate = QtCore.QCoreApplication.translate
        HostsEditor.setWindowTitle(_translate("HostsEditor", "Hosts Editor"))
        self.addBtn.setText(_translate("HostsEditor", "Add new rule"))
        self.editBtn.setText(_translate("HostsEditor", "Edit rule"))
        self.deleteBtn.setText(_translate("HostsEditor", "Delete rule"))
        self.scheduleBtn.setText(_translate("HostsEditor", "Schedule"))
        self.ieBtn.setText(_translate("HostsEditor", "Import/Export"))
        self.settingsBtn.setText(_translate("HostsEditor", "Settings"))
        self.exitBtn.setText(_translate("HostsEditor", "Exit"))
        self.infoBtn.setText(_translate("HostsEditor", "About"))
        self.resetBtn.setText(_translate("HostsEditor", "Reset"))
        self.saveBtn.setText(_translate("HostsEditor", "Save"))
